name: everdell
services:
  api:
    container_name: api
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./
    environment:
      - MODEL_PATH=${MODEL_PATH}
    ports:
      - 8080:8080